alias pacs 'sudo pacman -Ss'
alias paci 'sudo pacman -Si'
alias pacI 'sudo pacman -S'
alias pacu 'sudo pacman -Su'
alias pacU 'sudo pacman -Syu'
alias pacr 'sudo pacman -Rsu'
alias parus 'paru -Ss'
alias parui 'paru -Si'
alias paruI 'paru -S'
alias paruu 'paru -Su'
alias parur 'paru -Rsu'
