alias scoops 'scoop search'
alias scoopi 'scoop info'
alias scoopI 'scoop install'
alias scoopu 'scoop update'
alias scoopU 'scoop update --all'
alias scoopr 'scoop uninstall'
alias scoopc 'scoop cache rm --all'
