alias scoops 'scoop search'
alias scoopi 'scoop info'
alias scoopI 'scoop install'
alias scoopu 'scoop update && scoop status'
alias scoopU 'scoop update --all'
alias scoopr 'scoop uninstall -p'
alias scoopc 'scoop cache rm --all && scoop cleanup -ak'
