abbr -a scoops 'scoop search'
abbr -a scoopi 'scoop info'
abbr -a scoopI 'scoop install'
abbr -a scoopu 'scoop update && scoop status'
abbr -a scoopU 'scoop update --all'
abbr -a scoopr 'scoop uninstall -p'
abbr -a scoopc 'scoop cache rm --all && scoop cleanup -ak'
