patch:
  # punctuator/full_shape:
  punctuator/half_shape:
    "#": "#"
    "[": ["【", "「", "〔", "［", "〚", "〘"]
    "]": ["】", "」", "〕", "］", "〛", "〙"]
    "\\": "、"
    "/": ["/", "／", "÷", "、", "､"]
    "=": "="
    "`": "`"
    "|": ["|", "｜", "·", "・", "§", "¦", "‖", "︴"]
    "~": ["~", "≈", "～", "˜", "˷", "ⸯ", "≋", "≃", "≅", "≇", "∽"]
  schema/name: "中 - 朙月"
  switches:
    - name: ascii_mode
      reset: 1                # reset 0 的作用是當從其他輸入方案切換到本方案時，
